import moment from "moment";

export const debitRegisterEntries = [
  {
    amount: -200,
    balance: 1200,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: false,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: -100,
    balance: 1000,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: false,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: 100,
    balance: 900,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: false,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: 0,
    balance: 1000,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: true,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: -100,
    balance: 900,
    createdAt: moment("2025-02-02"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: true,
    isProjected: false,
  },
  {
    amount: 300,
    balance: 1200,
    createdAt: moment("2025-02-03"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: 200,
    balance: 1400,
    createdAt: moment("2025-02-03"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: -200,
    balance: 1200,
    createdAt: moment("2025-02-03"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
];

export const creditRegisterEntries = [
  {
    amount: 200,
    balance: -200,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: false,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: 100,
    balance: 0,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: false,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: -100,
    balance: 100,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: false,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: 0,
    balance: 0,
    createdAt: moment("2025-01-01"),
    isBalanceEntry: true,
    isCleared: true,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: -100,
    balance: -100,
    createdAt: moment("2025-02-02"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: true,
    isProjected: false,
  },
  {
    amount: -200,
    balance: -300,
    createdAt: moment("2025-02-03"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: -100,
    balance: -400,
    createdAt: moment("2025-02-03"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
  {
    amount: 400,
    balance: 0,
    createdAt: moment("2025-02-03"),
    isBalanceEntry: false,
    isCleared: false,
    isManualEntry: false,
    isPending: false,
    isProjected: false,
  },
];
