// This file was generated by prisma-field-encryption.

import type { PrismaClient } from '@prisma/client'
import { migrate as migrateUser } from './User'
import { migrate as migrateAccountRegister } from './AccountRegister'
import { migrate as migrateRegisterEntry } from './RegisterEntry'
import { migrate as migrateReoccurrence } from './Reoccurrence'
import type { ProgressReportCallback } from './progressReport'
import { defaultProgressReport } from './progressReport'

export type { ProgressReport, ProgressReportCallback } from './progressReport'
export { defaultProgressReport } from './progressReport'

// --

export type MigrationReport = {
  User: number,
  AccountRegister: number,
  RegisterEntry: number,
  Reoccurrence: number
}

/**
 * Migrate models concurrently.
 *
 * Processed models:
 * - User
 * - AccountRegister
 * - RegisterEntry
 * - Reoccurrence
 *
 * @returns a dictionary of the number of processed records per model.
 */
export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<MigrationReport> {
  const [
    processedUser,
    processedAccountRegister,
    processedRegisterEntry,
    processedReoccurrence
  ] = await Promise.all([
    migrateUser(client, reportProgress),
    migrateAccountRegister(client, reportProgress),
    migrateRegisterEntry(client, reportProgress),
    migrateReoccurrence(client, reportProgress)
  ])
  return {
    User: processedUser,
    AccountRegister: processedAccountRegister,
    RegisterEntry: processedRegisterEntry,
    Reoccurrence: processedReoccurrence
  }
}
