// This file was generated by prisma-field-encryption.

import type { PrismaClient, AccountRegister } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = AccountRegister['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'AccountRegister',
    client,
    getTotalCount: client.accountRegister.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.accountRegister.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        name: true,
        plaidId: true,
        plaidAccessToken: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.accountRegister.update({
      where: {
        id: record.id
      },
      data: {
        name: record.name,
        plaidId: record.plaidId,
        plaidAccessToken: record.plaidAccessToken
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "name": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "plaidId": {
 *       "encrypt": true,
 *       "strictDecryption": false,
 *       "hash": {
 *         "targetField": "plaidIdHash",
 *         "algorithm": "sha512",
 *         "inputEncoding": "utf8",
 *         "outputEncoding": "hex",
 *         "normalize": []
 *       }
 *     },
 *     "plaidAccessToken": {
 *       "encrypt": true,
 *       "strictDecryption": false,
 *       "hash": {
 *         "targetField": "plaidAccessTokenHash",
 *         "algorithm": "sha512",
 *         "inputEncoding": "utf8",
 *         "outputEncoding": "hex",
 *         "normalize": []
 *       }
 *     }
 *   },
 *   "connections": {
 *     "budget": {
 *       "modelName": "Budget",
 *       "isList": false
 *     },
 *     "type": {
 *       "modelName": "AccountType",
 *       "isList": false
 *     },
 *     "account": {
 *       "modelName": "Account",
 *       "isList": false
 *     },
 *     "reoccurrences": {
 *       "modelName": "Reoccurrence",
 *       "isList": true
 *     },
 *     "entries": {
 *       "modelName": "RegisterEntry",
 *       "isList": true
 *     },
 *     "parent": {
 *       "modelName": "AccountRegister",
 *       "isList": false
 *     },
 *     "children": {
 *       "modelName": "AccountRegister",
 *       "isList": true
 *     }
 *   }
 * }
 */
