apiVersion: apps/v1
kind: Deployment
metadata:
  name: dineros-production-deployment
  labels:
    app: dineros-production
  namespace: gs-services
spec:
  selector:
    matchLabels:
      app: dineros-production
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Updated at $(date +%s)"
      labels:
        app: dineros-production
    spec:
      serviceAccountName: dineros
      containers:
        - name: dineros-production-container
          image: gcr.io/nextstepguru/dineros:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-account-volume
              mountPath: /etc/google-service-account
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "mysql://production-dineros:production-dineros@10.127.192.3:3306/production-dineros"
            - name: NATS_URL
              value: "nats://nats.nats.svc.cluster.local:4222"
            - name: DEPLOY_ENV
              value: "production"
            - name: PORT
              value: "80"
            - name: GCP_PROJECT_ID
              value: "nextstepguru"
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dineros-secrets
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: dineros-secrets
                  key: TWILIO_ACCOUNT_SID
            - name: NODE_ENV
              value: "production"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"
            - name: SHOW_BULL_MQ_ADMIN
              value: "true"
            - name: PROJECT_NAME
              value: "comm"
            - name: POSTMARK_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dineros-secrets
                  key: POSTMARK_SERVER_TOKEN
            - name: POSTMARK_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: dineros-secrets
                  key: POSTMARK_WEBHOOK_SECRET
            - name: DB_DECRYPTION_KEY_1
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_1
            - name: DB_DECRYPTION_KEY_2
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_2
            - name: DB_DECRYPTION_KEY_3
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_3
            - name: DB_DECRYPTION_KEY_4
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_4
            - name: DB_DECRYPTION_KEY_5
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_5
            - name: DB_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_ENCRYPTION_KEY
            - name: CHAT_GPT_API
              valueFrom:
                secretKeyRef:
                  name: production-chat-gpt
                  key: CHAT_GPT_API
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: production-gs-secrets
                  key: DINEROS_JWT_SECRET
            - name: GCLOUD_KEY_NAME
              value: "./cloud-logging.json"
            - name: PLAID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dineros-secrets
                  key: PLAID_CLIENT_ID
            - name: PLAID_SECRET
              valueFrom:
                secretKeyRef:
                  name: dineros-secrets
                  key: PLAID_SECRET
            - name: NUXT_UI_PRO_LICENSE
              valueFrom:
                secretKeyRef:
                  name: dineros-secrets
                  key: NUXT_UI_PRO_LICENSE
            - name: DEBUG
              value: "dineros:*"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/google-service-account/service-account.json
          readinessProbe:
            httpGet:
              path: /api/_ah/readiness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/_ah/liveness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: service-account-volume
          secret:
            secretName: google-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dineros-microservice-production-deployment
  labels:
    app: dineros-microservice-production
  namespace: gs-services
spec:
  selector:
    matchLabels:
      app: dineros-microservice-production
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Updated at $(date +%s)"
      labels:
        app: dineros-microservice-production
    spec:
      serviceAccountName: dineros
      containers:
        - name: dineros-microservice-production-container
          image: gcr.io/nextstepguru/dineros-microservice:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-account-volume
              mountPath: /etc/google-service-account
              readOnly: true
          ports:
            - name: http
              containerPort: 3050
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "mysql://production-dineros:production-dineros@10.127.192.3:3306/production-dineros"
            - name: DEPLOY_ENV
              value: "production"
            - name: PORT
              value: "3050"
            - name: NODE_ENV
              value: "production"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"
            - name: DB_DECRYPTION_KEY_1
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_1
            - name: DB_DECRYPTION_KEY_2
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_2
            - name: DB_DECRYPTION_KEY_3
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_3
            - name: DB_DECRYPTION_KEY_4
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_4
            - name: DB_DECRYPTION_KEY_5
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_DECRYPTION_KEY_5
            - name: DB_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: production-db-secrets
                  key: DB_ENCRYPTION_KEY
      volumes:
        - name: service-account-volume
          secret:
            secretName: google-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: dineros-production-service
  labels:
    app: dineros-production
  namespace: gs-services
spec:
  selector:
    app: dineros-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  generation: 1
  labels:
    app: dineros-production
  name: dineros-production-ingress
  namespace: gs-services
spec:
  rules:
    - host: dineros.cc
      http:
        paths:
          - backend:
              service:
                name: dineros-production-service
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
    - host: www.dineros.cc
      http:
        paths:
          - backend:
              service:
                name: dineros-production-service
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - dineros.cc
        - www.dineros.cc
      secretName: dineros-production-tls
