/** Plaid personal_finance_category.detailed → category path (nature, not purpose). */
export const PLAID_PFC_DETAILED_TO_PATH: Record<string, string> = {
  INCOME_DIVIDENDS: "Income / Dividend Income",
  INCOME_INTEREST_EARNED: "Income / Interest Income",
  INCOME_RETIREMENT_PENSION: "Income / Salary & Wages",
  INCOME_TAX_REFUND: "Income / Refunds & Reimbursements",
  INCOME_UNEMPLOYMENT: "Income / Other Income",
  INCOME_WAGES: "Income / Salary & Wages",
  INCOME_OTHER_INCOME: "Income / Other Income",
  TRANSFER_IN_CASH_ADVANCES_AND_LOANS: "Transfers / Account Transfer",
  TRANSFER_IN_DEPOSIT: "Transfers / Account Transfer",
  TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS: "Savings & Investments / Brokerage / Taxable",
  TRANSFER_IN_SAVINGS: "Transfers / Internal Transfer",
  TRANSFER_IN_ACCOUNT_TRANSFER: "Transfers / Account Transfer",
  TRANSFER_IN_OTHER_TRANSFER_IN: "Transfers / Account Transfer",
  TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS: "Savings & Investments / Brokerage / Taxable",
  TRANSFER_OUT_SAVINGS: "Transfers / Internal Transfer",
  TRANSFER_OUT_WITHDRAWAL: "Transfers / Account Transfer",
  TRANSFER_OUT_ACCOUNT_TRANSFER: "Transfers / Account Transfer",
  TRANSFER_OUT_OTHER_TRANSFER_OUT: "Transfers / Account Transfer",
  LOAN_PAYMENTS_CAR_PAYMENT: "Transportation / Auto Payment / Lease",
  LOAN_PAYMENTS_CREDIT_CARD_PAYMENT: "Debt Payments / Credit Card Payment",
  LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT: "Debt Payments / Personal Loan",
  LOAN_PAYMENTS_MORTGAGE_PAYMENT: "Housing / Rent & Mortgage",
  LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT: "Debt Payments / Student Loan",
  LOAN_PAYMENTS_OTHER_PAYMENT: "Debt Payments / Other Debt",
  BANK_FEES_ATM_FEES: "Transfers / Account Transfer",
  BANK_FEES_OVERDRAFT_FEES: "Transfers / Account Transfer",
  BANK_FEES_OTHER_BANK_FEES: "Transfers / Account Transfer",
  ENTERTAINMENT_CASINOS_AND_GAMBLING: "Entertainment / Games & Events",
  ENTERTAINMENT_MUSIC_AND_AUDIO: "Entertainment / Streaming & Media",
  ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS:
    "Entertainment / Sports & Recreation",
  ENTERTAINMENT_TV_AND_MOVIES: "Entertainment / Streaming & Media",
  ENTERTAINMENT_VIDEO_GAMES: "Entertainment / Games & Events",
  ENTERTAINMENT_OTHER_ENTERTAINMENT: "Entertainment / Hobbies",
  FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR: "Food & Dining / Alcohol & Bars",
  FOOD_AND_DRINK_COFFEE: "Food & Dining / Coffee & Snacks",
  FOOD_AND_DRINK_FAST_FOOD: "Food & Dining / Restaurants & Takeout",
  FOOD_AND_DRINK_GROCERIES: "Food & Dining / Groceries",
  FOOD_AND_DRINK_RESTAURANT: "Food & Dining / Restaurants & Takeout",
  FOOD_AND_DRINK_VENDING_MACHINES: "Food & Dining / Coffee & Snacks",
  FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK: "Food & Dining / Restaurants & Takeout",
  GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS: "Shopping / General Merchandise",
  GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES: "Personal Care / Clothing",
  GENERAL_MERCHANDISE_CONVENIENCE_STORES: "Food & Dining / Coffee & Snacks",
  GENERAL_MERCHANDISE_DEPARTMENT_STORES: "Shopping / General Merchandise",
  GENERAL_MERCHANDISE_DISCOUNT_STORES: "Shopping / General Merchandise",
  GENERAL_MERCHANDISE_ELECTRONICS: "Shopping / Electronics",
  GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES: "Gifts & Donations / Gifts",
  GENERAL_MERCHANDISE_OFFICE_SUPPLIES: "Business / Office Supplies",
  GENERAL_MERCHANDISE_ONLINE_MARKETPLACES: "Shopping / General Merchandise",
  GENERAL_MERCHANDISE_PET_SUPPLIES: "Pets / Food & Supplies",
  GENERAL_MERCHANDISE_SPORTING_GOODS: "Entertainment / Sports & Recreation",
  GENERAL_MERCHANDISE_SUPERSTORES: "Shopping / General Merchandise",
  GENERAL_MERCHANDISE_TOBACCO_AND_VAPE: "Shopping / General Merchandise",
  GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE: "Shopping / General Merchandise",
  HOME_IMPROVEMENT_FURNITURE: "Housing / Furnishings",
  HOME_IMPROVEMENT_HARDWARE: "Housing / Maintenance & Repairs",
  HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE: "Housing / Maintenance & Repairs",
  HOME_IMPROVEMENT_SECURITY: "Housing / Maintenance & Repairs",
  HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT: "Housing / Maintenance & Repairs",
  MEDICAL_DENTAL_CARE: "Healthcare / Dental",
  MEDICAL_EYE_CARE: "Healthcare / Vision",
  MEDICAL_NURSING_CARE: "Healthcare / Doctor & Clinic",
  MEDICAL_PHARMACIES_AND_SUPPLEMENTS: "Healthcare / Pharmacy",
  MEDICAL_PRIMARY_CARE: "Healthcare / Doctor & Clinic",
  MEDICAL_VETERINARY_SERVICES: "Pets / Vet & Medical",
  MEDICAL_OTHER_MEDICAL: "Healthcare / Doctor & Clinic",
  PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS: "Healthcare / Gym & Fitness",
  PERSONAL_CARE_HAIR_AND_BEAUTY: "Personal Care / Haircuts & Spa",
  PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING: "Personal Care / Personal Items",
  PERSONAL_CARE_OTHER_PERSONAL_CARE: "Personal Care / Personal Items",
  GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING: "Business / Professional Services",
  GENERAL_SERVICES_AUTOMOTIVE: "Transportation / Maintenance & Repairs",
  GENERAL_SERVICES_CHILDCARE: "Personal Care / Personal Items",
  GENERAL_SERVICES_CONSULTING_AND_LEGAL: "Business / Professional Services",
  GENERAL_SERVICES_EDUCATION: "Education / Courses & Training",
  GENERAL_SERVICES_INSURANCE: "Insurance / Other Insurance",
  GENERAL_SERVICES_POSTAGE_AND_SHIPPING: "Shopping / General Merchandise",
  GENERAL_SERVICES_STORAGE: "Housing / Maintenance & Repairs",
  GENERAL_SERVICES_OTHER_GENERAL_SERVICES: "Business / Professional Services",
  GOVERNMENT_AND_NON_PROFIT_DONATIONS: "Gifts & Donations / Charity & Donations",
  GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES: "Taxes / Federal Income Tax",
  GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT: "Taxes / Federal Income Tax",
  GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT: "Taxes / State & Local Tax",
  TRANSPORTATION_BIKES_AND_SCOOTERS: "Transportation / Public Transit",
  TRANSPORTATION_GAS: "Transportation / Fuel",
  TRANSPORTATION_PARKING: "Transportation / Parking & Tolls",
  TRANSPORTATION_PUBLIC_TRANSIT: "Transportation / Public Transit",
  TRANSPORTATION_TAXIS_AND_RIDE_SHARES: "Transportation / Rideshare",
  TRANSPORTATION_TOLLS: "Transportation / Parking & Tolls",
  TRANSPORTATION_OTHER_TRANSPORTATION: "Transportation / Fuel",
  TRAVEL_FLIGHTS: "Travel / Flights",
  TRAVEL_LODGING: "Travel / Lodging",
  TRAVEL_RENTAL_CARS: "Travel / Rental Car",
  TRAVEL_OTHER_TRAVEL: "Travel / Vacation & Activities",
  RENT_AND_UTILITIES_GAS_AND_ELECTRICITY: "Utilities / Electric",
  RENT_AND_UTILITIES_GAS: "Utilities / Natural Gas",
  RENT_AND_UTILITIES_INTERNET_AND_CABLE: "Utilities / Internet",
  RENT_AND_UTILITIES_RENT: "Housing / Rent & Mortgage",
  RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT: "Utilities / Trash & Recycling",
  RENT_AND_UTILITIES_TELEPHONE: "Utilities / Phone & Mobile",
  RENT_AND_UTILITIES_WATER: "Utilities / Water & Sewer",
  RENT_AND_UTILITIES_OTHER_UTILITIES: "Utilities / Electric",
};

const HIGH_PFC_CONFIDENCE = new Set(["VERY_HIGH", "HIGH"]);

export function isHighPfcConfidence(level: string | null | undefined): boolean {
  if (!level) return false;
  return HIGH_PFC_CONFIDENCE.has(level.toUpperCase());
}

export function pathForPfcDetailed(detailed: string | null | undefined): string | null {
  if (!detailed) return null;
  return PLAID_PFC_DETAILED_TO_PATH[detailed.toUpperCase()] ?? null;
}
