// This file was generated by prisma-field-encryption.

import type { PrismaClient } from '@prisma/client'
import { migrate as migrateUser } from './User'
import { migrate as migrateAccountRegister } from './AccountRegister'
import { migrate as migrateRegisterEntry } from './RegisterEntry'
import { migrate as migrateReoccurrence } from './Reoccurrence'

export interface ProgressReport {
  model: string
  processed: number
  totalCount: number
  performance: number
}

export type ProgressReportCallback = (
  progress: ProgressReport
) => void | Promise<void>

export const defaultProgressReport: ProgressReportCallback = ({
  model,
  totalCount,
  processed,
  performance
}) => {
  const length = totalCount.toString().length
  const pct = Math.round((100 * processed) / totalCount)
    .toString()
    .padStart(3)
  console.info(
    `${model.padEnd(15)} ${pct}% processed ${processed
      .toString()
      .padStart(length)} / ${totalCount} (took ${performance.toFixed(2)}ms)`
  )
}

// --

export type MigrationReport = {
  User: number,
  AccountRegister: number,
  RegisterEntry: number,
  Reoccurrence: number
}

/**
 * Migrate models concurrently.
 *
 * Processed models:
 * - User
 * - AccountRegister
 * - RegisterEntry
 * - Reoccurrence
 *
 * @returns a dictionary of the number of processed records per model.
 */
export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<MigrationReport> {
  const [
    processedUser,
    processedAccountRegister,
    processedRegisterEntry,
    processedReoccurrence
  ] = await Promise.all([
    migrateUser(client, reportProgress),
    migrateAccountRegister(client, reportProgress),
    migrateRegisterEntry(client, reportProgress),
    migrateReoccurrence(client, reportProgress)
  ])
  return {
    User: processedUser,
    AccountRegister: processedAccountRegister,
    RegisterEntry: processedRegisterEntry,
    Reoccurrence: processedReoccurrence
  }
}
