// This file was generated by prisma-field-encryption.

import type { PrismaClient, RegisterEntry } from '@prisma/client'
import type {
  ProgressReportCallback} from 'prisma-field-encryption/dist/generator/runtime';
import {
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = RegisterEntry['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'RegisterEntry',
    client,
    getTotalCount: client.registerEntry.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.registerEntry.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        description: true,
        plaidId: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.registerEntry.update({
      where: {
        id: record.id
      },
      data: {
        description: record.description,
        plaidId: record.plaidId
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "description": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "plaidId": {
 *       "encrypt": true,
 *       "strictDecryption": false,
 *       "hash": {
 *         "targetField": "plaidIdHash",
 *         "algorithm": "sha512",
 *         "inputEncoding": "utf8",
 *         "outputEncoding": "hex",
 *         "normalize": []
 *       }
 *     }
 *   },
 *   "connections": {
 *     "register": {
 *       "modelName": "AccountRegister",
 *       "isList": false
 *     },
 *     "reoccurrence": {
 *       "modelName": "Reoccurrence",
 *       "isList": false
 *     },
 *     "type": {
 *       "modelName": "RegisterEntryType",
 *       "isList": false
 *     },
 *     "category": {
 *       "modelName": "Category",
 *       "isList": false
 *     },
 *     "billInstancesPaid": {
 *       "modelName": "BillInstance",
 *       "isList": true
 *     },
 *     "reconciliationItems": {
 *       "modelName": "ReconciliationItem",
 *       "isList": true
 *     },
 *     "reconciliationClosingPeriods": {
 *       "modelName": "ReconciliationPeriod",
 *       "isList": true
 *     }
 *   }
 * }
 */
