// This file was generated by prisma-field-encryption.

import type { PrismaClient, Reoccurrence } from '@prisma/client'
import type { ProgressReportCallback } from 'prisma-field-encryption/dist/generator/runtime'
import {
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = Reoccurrence['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'Reoccurrence',
    client,
    getTotalCount: client.reoccurrence.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.reoccurrence.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        description: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.reoccurrence.update({
      where: {
        id: record.id
      },
      data: {
        description: record.description
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "description": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "account": {
 *       "modelName": "Account",
 *       "isList": false
 *     },
 *     "register": {
 *       "modelName": "AccountRegister",
 *       "isList": false
 *     },
 *     "interval": {
 *       "modelName": "Interval",
 *       "isList": false
 *     },
 *     "amountAdjustmentInterval": {
 *       "modelName": "Interval",
 *       "isList": false
 *     },
 *     "category": {
 *       "modelName": "Category",
 *       "isList": false
 *     },
 *     "entries": {
 *       "modelName": "RegisterEntry",
 *       "isList": true
 *     },
 *     "skips": {
 *       "modelName": "ReoccurrenceSkip",
 *       "isList": true
 *     },
 *     "splits": {
 *       "modelName": "ReoccurrenceSplit",
 *       "isList": true
 *     },
 *     "plaidNameAliases": {
 *       "modelName": "ReoccurrencePlaidNameAlias",
 *       "isList": true
 *     },
 *     "billProfile": {
 *       "modelName": "BillProfile",
 *       "isList": false
 *     },
 *     "billInstances": {
 *       "modelName": "BillInstance",
 *       "isList": true
 *     }
 *   }
 * }
 */
