// This file was generated by prisma-field-encryption.

import type { PrismaClient, User } from "@prisma/client";
import {
  type ProgressReportCallback,
  defaultProgressReport,
  visitRecords,
} from "prisma-field-encryption/dist/generator/runtime";

type Cursor = User["id"];

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport,
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: "User",
    client,
    getTotalCount: client.user.count,
    migrateRecord,
    reportProgress,
  });
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async (tx) => {
    const record = await tx.user.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor,
            },
          }),
      orderBy: {
        id: "asc",
      },
      select: {
        id: true,
        email: true,
        password: true,
      },
    });
    if (!record) {
      return cursor;
    }
    await tx.user.update({
      where: {
        id: record.id,
      },
      data: {
        email: record.email,
        password: record.password,
      },
    });
    return record.id;
  });
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "email": {
 *       "encrypt": true,
 *       "strictDecryption": false,
 *       "hash": {
 *         "targetField": "emailHash",
 *         "algorithm": "sha512",
 *         "inputEncoding": "utf8",
 *         "outputEncoding": "hex",
 *         "normalize": []
 *       }
 *     },
 *     "password": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "budgets": {
 *       "modelName": "Budget",
 *       "isList": true
 *     },
 *     "social": {
 *       "modelName": "UserSocial",
 *       "isList": true
 *     },
 *     "accounts": {
 *       "modelName": "UserAccount",
 *       "isList": true
 *     },
 *     "accountInvitesSent": {
 *       "modelName": "AccountInvite",
 *       "isList": true
 *     },
 *     "country": {
 *       "modelName": "Country",
 *       "isList": false
 *     },
 *     "plaidItems": {
 *       "modelName": "PlaidItem",
 *       "isList": true
 *     },
 *     "notifications": {
 *       "modelName": "NotificationEvent",
 *       "isList": true
 *     },
 *     "notificationDismissals": {
 *       "modelName": "NotificationDismissal",
 *       "isList": true
 *     },
 *     "reconciliationPeriodsClosed": {
 *       "modelName": "ReconciliationPeriod",
 *       "isList": true
 *     }
 *   }
 * }
 */
