-- Populate country table (ISO 3166-1: id = numeric, code = alpha-2, code3 = alpha-3)
-- Run with: mysql -u user -p database_name < prisma/seed-country.sql
-- Or execute in TablePlus / your DB client.

INSERT INTO `country` (`id`, `name`, `code`, `code3`, `is_active`, `created_at`, `updated_at`) VALUES
(4, 'Afghanistan', 'AF', 'AFG', 1, NOW(), NOW()),
(8, 'Albania', 'AL', 'ALB', 1, NOW(), NOW()),
(12, 'Algeria', 'DZ', 'DZA', 1, NOW(), NOW()),
(20, 'Andorra', 'AD', 'AND', 1, NOW(), NOW()),
(24, 'Angola', 'AO', 'AGO', 1, NOW(), NOW()),
(28, 'Antigua and Barbuda', 'AG', 'ATG', 1, NOW(), NOW()),
(32, 'Argentina', 'AR', 'ARG', 1, NOW(), NOW()),
(51, 'Armenia', 'AM', 'ARM', 1, NOW(), NOW()),
(36, 'Australia', 'AU', 'AUS', 1, NOW(), NOW()),
(40, 'Austria', 'AT', 'AUT', 1, NOW(), NOW()),
(31, 'Azerbaijan', 'AZ', 'AZE', 1, NOW(), NOW()),
(44, 'Bahamas', 'BS', 'BHS', 1, NOW(), NOW()),
(48, 'Bahrain', 'BH', 'BHR', 1, NOW(), NOW()),
(50, 'Bangladesh', 'BD', 'BGD', 1, NOW(), NOW()),
(52, 'Barbados', 'BB', 'BRB', 1, NOW(), NOW()),
(112, 'Belarus', 'BY', 'BLR', 1, NOW(), NOW()),
(56, 'Belgium', 'BE', 'BEL', 1, NOW(), NOW()),
(84, 'Belize', 'BZ', 'BLZ', 1, NOW(), NOW()),
(204, 'Benin', 'BJ', 'BEN', 1, NOW(), NOW()),
(64, 'Bhutan', 'BT', 'BTN', 1, NOW(), NOW()),
(68, 'Bolivia (Plurinational State of)', 'BO', 'BOL', 1, NOW(), NOW()),
(70, 'Bosnia and Herzegovina', 'BA', 'BIH', 1, NOW(), NOW()),
(72, 'Botswana', 'BW', 'BWA', 1, NOW(), NOW()),
(76, 'Brazil', 'BR', 'BRA', 1, NOW(), NOW()),
(96, 'Brunei Darussalam', 'BN', 'BRN', 1, NOW(), NOW()),
(100, 'Bulgaria', 'BG', 'BGR', 1, NOW(), NOW()),
(854, 'Burkina Faso', 'BF', 'BFA', 1, NOW(), NOW()),
(108, 'Burundi', 'BI', 'BDI', 1, NOW(), NOW()),
(132, 'Cabo Verde', 'CV', 'CPV', 1, NOW(), NOW()),
(116, 'Cambodia', 'KH', 'KHM', 1, NOW(), NOW()),
(120, 'Cameroon', 'CM', 'CMR', 1, NOW(), NOW()),
(124, 'Canada', 'CA', 'CAN', 1, NOW(), NOW()),
(140, 'Central African Republic', 'CF', 'CAF', 1, NOW(), NOW()),
(148, 'Chad', 'TD', 'TCD', 1, NOW(), NOW()),
(152, 'Chile', 'CL', 'CHL', 1, NOW(), NOW()),
(156, 'China', 'CN', 'CHN', 1, NOW(), NOW()),
(170, 'Colombia', 'CO', 'COL', 1, NOW(), NOW()),
(174, 'Comoros', 'KM', 'COM', 1, NOW(), NOW()),
(178, 'Congo', 'CG', 'COG', 1, NOW(), NOW()),
(180, 'Congo (Democratic Republic of the)', 'CD', 'COD', 1, NOW(), NOW()),
(188, 'Costa Rica', 'CR', 'CRI', 1, NOW(), NOW()),
(384, 'Côte d''Ivoire', 'CI', 'CIV', 1, NOW(), NOW()),
(191, 'Croatia', 'HR', 'HRV', 1, NOW(), NOW()),
(192, 'Cuba', 'CU', 'CUB', 1, NOW(), NOW()),
(196, 'Cyprus', 'CY', 'CYP', 1, NOW(), NOW()),
(203, 'Czechia', 'CZ', 'CZE', 1, NOW(), NOW()),
(208, 'Denmark', 'DK', 'DNK', 1, NOW(), NOW()),
(262, 'Djibouti', 'DJ', 'DJI', 1, NOW(), NOW()),
(212, 'Dominica', 'DM', 'DMA', 1, NOW(), NOW()),
(214, 'Dominican Republic', 'DO', 'DOM', 1, NOW(), NOW()),
(218, 'Ecuador', 'EC', 'ECU', 1, NOW(), NOW()),
(818, 'Egypt', 'EG', 'EGY', 1, NOW(), NOW()),
(222, 'El Salvador', 'SV', 'SLV', 1, NOW(), NOW()),
(226, 'Equatorial Guinea', 'GQ', 'GNQ', 1, NOW(), NOW()),
(232, 'Eritrea', 'ER', 'ERI', 1, NOW(), NOW()),
(233, 'Estonia', 'EE', 'EST', 1, NOW(), NOW()),
(748, 'Eswatini', 'SZ', 'SWZ', 1, NOW(), NOW()),
(231, 'Ethiopia', 'ET', 'ETH', 1, NOW(), NOW()),
(242, 'Fiji', 'FJ', 'FJI', 1, NOW(), NOW()),
(246, 'Finland', 'FI', 'FIN', 1, NOW(), NOW()),
(250, 'France', 'FR', 'FRA', 1, NOW(), NOW()),
(266, 'Gabon', 'GA', 'GAB', 1, NOW(), NOW()),
(270, 'Gambia', 'GM', 'GMB', 1, NOW(), NOW()),
(268, 'Georgia', 'GE', 'GEO', 1, NOW(), NOW()),
(276, 'Germany', 'DE', 'DEU', 1, NOW(), NOW()),
(288, 'Ghana', 'GH', 'GHA', 1, NOW(), NOW()),
(300, 'Greece', 'GR', 'GRC', 1, NOW(), NOW()),
(308, 'Grenada', 'GD', 'GRD', 1, NOW(), NOW()),
(320, 'Guatemala', 'GT', 'GTM', 1, NOW(), NOW()),
(324, 'Guinea', 'GN', 'GIN', 1, NOW(), NOW()),
(624, 'Guinea-Bissau', 'GW', 'GNB', 1, NOW(), NOW()),
(328, 'Guyana', 'GY', 'GUY', 1, NOW(), NOW()),
(332, 'Haiti', 'HT', 'HTI', 1, NOW(), NOW()),
(340, 'Honduras', 'HN', 'HND', 1, NOW(), NOW()),
(348, 'Hungary', 'HU', 'HUN', 1, NOW(), NOW()),
(352, 'Iceland', 'IS', 'ISL', 1, NOW(), NOW()),
(356, 'India', 'IN', 'IND', 1, NOW(), NOW()),
(360, 'Indonesia', 'ID', 'IDN', 1, NOW(), NOW()),
(364, 'Iran (Islamic Republic of)', 'IR', 'IRN', 1, NOW(), NOW()),
(368, 'Iraq', 'IQ', 'IRQ', 1, NOW(), NOW()),
(372, 'Ireland', 'IE', 'IRL', 1, NOW(), NOW()),
(376, 'Israel', 'IL', 'ISR', 1, NOW(), NOW()),
(380, 'Italy', 'IT', 'ITA', 1, NOW(), NOW()),
(388, 'Jamaica', 'JM', 'JAM', 1, NOW(), NOW()),
(392, 'Japan', 'JP', 'JPN', 1, NOW(), NOW()),
(400, 'Jordan', 'JO', 'JOR', 1, NOW(), NOW()),
(398, 'Kazakhstan', 'KZ', 'KAZ', 1, NOW(), NOW()),
(404, 'Kenya', 'KE', 'KEN', 1, NOW(), NOW()),
(296, 'Kiribati', 'KI', 'KIR', 1, NOW(), NOW()),
(408, 'Korea (Democratic People''s Republic of)', 'KP', 'PRK', 1, NOW(), NOW()),
(410, 'Korea (Republic of)', 'KR', 'KOR', 1, NOW(), NOW()),
(414, 'Kuwait', 'KW', 'KWT', 1, NOW(), NOW()),
(417, 'Kyrgyzstan', 'KG', 'KGZ', 1, NOW(), NOW()),
(418, 'Lao People''s Democratic Republic', 'LA', 'LAO', 1, NOW(), NOW()),
(428, 'Latvia', 'LV', 'LVA', 1, NOW(), NOW()),
(422, 'Lebanon', 'LB', 'LBN', 1, NOW(), NOW()),
(426, 'Lesotho', 'LS', 'LSO', 1, NOW(), NOW()),
(430, 'Liberia', 'LR', 'LBR', 1, NOW(), NOW()),
(434, 'Libya', 'LY', 'LBY', 1, NOW(), NOW()),
(438, 'Liechtenstein', 'LI', 'LIE', 1, NOW(), NOW()),
(440, 'Lithuania', 'LT', 'LTU', 1, NOW(), NOW()),
(442, 'Luxembourg', 'LU', 'LUX', 1, NOW(), NOW()),
(450, 'Madagascar', 'MG', 'MDG', 1, NOW(), NOW()),
(454, 'Malawi', 'MW', 'MWI', 1, NOW(), NOW()),
(458, 'Malaysia', 'MY', 'MYS', 1, NOW(), NOW()),
(462, 'Maldives', 'MV', 'MDV', 1, NOW(), NOW()),
(466, 'Mali', 'ML', 'MLI', 1, NOW(), NOW()),
(470, 'Malta', 'MT', 'MLT', 1, NOW(), NOW()),
(584, 'Marshall Islands', 'MH', 'MHL', 1, NOW(), NOW()),
(478, 'Mauritania', 'MR', 'MRT', 1, NOW(), NOW()),
(480, 'Mauritius', 'MU', 'MUS', 1, NOW(), NOW()),
(484, 'Mexico', 'MX', 'MEX', 1, NOW(), NOW()),
(583, 'Micronesia (Federated States of)', 'FM', 'FSM', 1, NOW(), NOW()),
(498, 'Moldova (Republic of)', 'MD', 'MDA', 1, NOW(), NOW()),
(492, 'Monaco', 'MC', 'MCO', 1, NOW(), NOW()),
(496, 'Mongolia', 'MN', 'MNG', 1, NOW(), NOW()),
(499, 'Montenegro', 'ME', 'MNE', 1, NOW(), NOW()),
(504, 'Morocco', 'MA', 'MAR', 1, NOW(), NOW()),
(508, 'Mozambique', 'MZ', 'MOZ', 1, NOW(), NOW()),
(104, 'Myanmar', 'MM', 'MMR', 1, NOW(), NOW()),
(516, 'Namibia', 'NA', 'NAM', 1, NOW(), NOW()),
(520, 'Nauru', 'NR', 'NRU', 1, NOW(), NOW()),
(524, 'Nepal', 'NP', 'NPL', 1, NOW(), NOW()),
(528, 'Netherlands', 'NL', 'NLD', 1, NOW(), NOW()),
(554, 'New Zealand', 'NZ', 'NZL', 1, NOW(), NOW()),
(558, 'Nicaragua', 'NI', 'NIC', 1, NOW(), NOW()),
(562, 'Niger', 'NE', 'NER', 1, NOW(), NOW()),
(566, 'Nigeria', 'NG', 'NGA', 1, NOW(), NOW()),
(807, 'North Macedonia', 'MK', 'MKD', 1, NOW(), NOW()),
(578, 'Norway', 'NO', 'NOR', 1, NOW(), NOW()),
(512, 'Oman', 'OM', 'OMN', 1, NOW(), NOW()),
(586, 'Pakistan', 'PK', 'PAK', 1, NOW(), NOW()),
(585, 'Palau', 'PW', 'PLW', 1, NOW(), NOW()),
(275, 'Palestine, State of', 'PS', 'PSE', 1, NOW(), NOW()),
(591, 'Panama', 'PA', 'PAN', 1, NOW(), NOW()),
(598, 'Papua New Guinea', 'PG', 'PNG', 1, NOW(), NOW()),
(600, 'Paraguay', 'PY', 'PRY', 1, NOW(), NOW()),
(604, 'Peru', 'PE', 'PER', 1, NOW(), NOW()),
(608, 'Philippines', 'PH', 'PHL', 1, NOW(), NOW()),
(616, 'Poland', 'PL', 'POL', 1, NOW(), NOW()),
(620, 'Portugal', 'PT', 'PRT', 1, NOW(), NOW()),
(634, 'Qatar', 'QA', 'QAT', 1, NOW(), NOW()),
(642, 'Romania', 'RO', 'ROU', 1, NOW(), NOW()),
(643, 'Russian Federation', 'RU', 'RUS', 1, NOW(), NOW()),
(646, 'Rwanda', 'RW', 'RWA', 1, NOW(), NOW()),
(659, 'Saint Kitts and Nevis', 'KN', 'KNA', 1, NOW(), NOW()),
(662, 'Saint Lucia', 'LC', 'LCA', 1, NOW(), NOW()),
(670, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 1, NOW(), NOW()),
(882, 'Samoa', 'WS', 'WSM', 1, NOW(), NOW()),
(674, 'San Marino', 'SM', 'SMR', 1, NOW(), NOW()),
(678, 'Sao Tome and Principe', 'ST', 'STP', 1, NOW(), NOW()),
(682, 'Saudi Arabia', 'SA', 'SAU', 1, NOW(), NOW()),
(686, 'Senegal', 'SN', 'SEN', 1, NOW(), NOW()),
(688, 'Serbia', 'RS', 'SRB', 1, NOW(), NOW()),
(690, 'Seychelles', 'SC', 'SYC', 1, NOW(), NOW()),
(694, 'Sierra Leone', 'SL', 'SLE', 1, NOW(), NOW()),
(702, 'Singapore', 'SG', 'SGP', 1, NOW(), NOW()),
(703, 'Slovakia', 'SK', 'SVK', 1, NOW(), NOW()),
(705, 'Slovenia', 'SI', 'SVN', 1, NOW(), NOW()),
(90, 'Solomon Islands', 'SB', 'SLB', 1, NOW(), NOW()),
(706, 'Somalia', 'SO', 'SOM', 1, NOW(), NOW()),
(710, 'South Africa', 'ZA', 'ZAF', 1, NOW(), NOW()),
(728, 'South Sudan', 'SS', 'SSD', 1, NOW(), NOW()),
(724, 'Spain', 'ES', 'ESP', 1, NOW(), NOW()),
(144, 'Sri Lanka', 'LK', 'LKA', 1, NOW(), NOW()),
(729, 'Sudan', 'SD', 'SDN', 1, NOW(), NOW()),
(740, 'Suriname', 'SR', 'SUR', 1, NOW(), NOW()),
(752, 'Sweden', 'SE', 'SWE', 1, NOW(), NOW()),
(756, 'Switzerland', 'CH', 'CHE', 1, NOW(), NOW()),
(760, 'Syrian Arab Republic', 'SY', 'SYR', 1, NOW(), NOW()),
(158, 'Taiwan, Province of China', 'TW', 'TWN', 1, NOW(), NOW()),
(762, 'Tajikistan', 'TJ', 'TJK', 1, NOW(), NOW()),
(834, 'Tanzania, United Republic of', 'TZ', 'TZA', 1, NOW(), NOW()),
(764, 'Thailand', 'TH', 'THA', 1, NOW(), NOW()),
(626, 'Timor-Leste', 'TL', 'TLS', 1, NOW(), NOW()),
(768, 'Togo', 'TG', 'TGO', 1, NOW(), NOW()),
(776, 'Tonga', 'TO', 'TON', 1, NOW(), NOW()),
(780, 'Trinidad and Tobago', 'TT', 'TTO', 1, NOW(), NOW()),
(788, 'Tunisia', 'TN', 'TUN', 1, NOW(), NOW()),
(795, 'Turkmenistan', 'TM', 'TKM', 1, NOW(), NOW()),
(798, 'Tuvalu', 'TV', 'TUV', 1, NOW(), NOW()),
(800, 'Uganda', 'UG', 'UGA', 1, NOW(), NOW()),
(804, 'Ukraine', 'UA', 'UKR', 1, NOW(), NOW()),
(784, 'United Arab Emirates', 'AE', 'ARE', 1, NOW(), NOW()),
(826, 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', 1, NOW(), NOW()),
(840, 'United States of America', 'US', 'USA', 1, NOW(), NOW()),
(858, 'Uruguay', 'UY', 'URY', 1, NOW(), NOW()),
(860, 'Uzbekistan', 'UZ', 'UZB', 1, NOW(), NOW()),
(548, 'Vanuatu', 'VU', 'VUT', 1, NOW(), NOW()),
(862, 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 1, NOW(), NOW()),
(704, 'Viet Nam', 'VN', 'VNM', 1, NOW(), NOW()),
(887, 'Yemen', 'YE', 'YEM', 1, NOW(), NOW()),
(894, 'Zambia', 'ZM', 'ZMB', 1, NOW(), NOW()),
(716, 'Zimbabwe', 'ZW', 'ZWE', 1, NOW(), NOW()),
(344, 'Hong Kong', 'HK', 'HKG', 1, NOW(), NOW()),
(446, 'Macao', 'MO', 'MAC', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `code3` = VALUES(`code3`),
  `is_active` = VALUES(`is_active`),
  `updated_at` = NOW();
